### ISSUE TITLE
Copy change

### ISSUE THREAD

**Issue by mflaxman** [merland/seedpicker#11]
There are 3 different multisig schemes that Electrum supports (p2sh, p2sh-wrapped-p2wsh, and p2wsh). You've implemented p2wsh (best choice), but that's going to be confusing to end users.

Since what you've implemented is called `native segwit multisig (p2wsh)` on Electrum, I'd recommend you add that copy.

Perhaps change to something like this?
`Extended Public Key in Zpub format (Suitable for use in an Electrum Multi-signature scheme)`
->
`Extended Public Key in Zpub format for Electrum's native segwit multisig (p2wsh)`

**Comment by merland** [comment]
Thanks for this, changed as suggested.
