### ISSUE TITLE
Rename to something like "electrum multisig seed generator"?

### ISSUE THREAD

**Issue by mflaxman** [merland/seedpicker#15]
There are other derivation schemes that future multisig tools may use, and the derivation path with SLIP132 is a uniquely Electrum implementation. It's currently the leading standard for multi hardware wallet multisig, but that's probably because it's the only decent GUI for sovereign end-users. With HWI and several multisig companies using their own scheme, I wouldn't be surprised if there are more future standards.

Another option would be to add support for advanced users to toggle every option: let users generate their own derivation path, pick their own SLIP-132 version bytes (p2sh, ps2h-wrapped segwit, p2wsh), pick their network (mainnet/testnet), etc. To me that would be a very cool for advanced users, but is less useful for 99% of normal users who are more likely to be confused and make a mistake.

**Comment by merland** [comment]
Naming is hard, especially when you are anticipating multiple pivots. Or none, we don't know much about the future :)  

This project started with the main focus on general generation of true randomness, but is now shifting over more to being a specialized tool for one particular use case. Which is good; It's easier to get quality feedback for a very narrow scenario and it can grow from there.
 
Personally I'm not at all against a name change, but I think we could wait a little bit to see in which direction the project will go in the coming weeks.  In the meantime, we could instead improve the description/instructions on the page, to make it clear what the exact purpose of this tool is.

**Comment by merland** [comment]
Closing since the project now is moving away from being an Electrum helper specifically. 
The SeedPicker name is not perfect, but it is (a bit) more established now.
