### ISSUE TITLE
Feature Request: Add Root Fingerprint to Output

### ISSUE THREAD

**Issue by mflaxman** [merland/seedpicker#23]
It turns out this is required for interoperability with Coldcard as well as [Spectre](https://github.com/cryptoadvance/specter-desktop).

The easiest way to do this now is as follows, but it's obviously sketchy (destroys much of the security benefit of seedpicker!):
1. Calculate last word for `abandon` repeated 23x here (will correctly return `art`):
http://seedpicker.net/calculator/last-word.html
2. Open up an Electrum console and input 24 words into this script:
```
>> from electrum import keystore
>> ks = keystore.from_bip39_seed("abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art", passphrase="", derivation="m/48'/0'/0'/2'")
>> ks.get_root_fingerprint()
'5436d724'
```
![Screen Shot 2020-08-20 at 10 52 49 AM](https://user-images.githubusercontent.com/448644/90795152-53323e80-e2d3-11ea-8922-ca8029c5f047.png)

Code snippet on how to calculate root fingerpint here:
https://github.com/spesmilo/electrum/blob/9d0bb295e6f55a2bff9f5b6770fa744c16af6e8a/electrum/keystore.py#L685-L690

This one may be easier to read:
https://github.com/lyndsysimon/bip32utils/blob/56f5a56d1c54e648f35b670a87efabbca08fffae/bip32utils/BIP32Key.py#L244-L266

Maybe for UX purposes, you'd want to hide this behind `Show more (for advanced users)`?

**Comment by merland** [comment]
I'm not so good at python (or golang), so I thought I'd look up the standard recipe for cooking a root fingerprint. Is this in any of the BIPs? I couldn't find it.

**Comment by mflaxman** [comment]
There isn't really, it's just something coldcard picked up for registering xpubs in a multisig and then Spectre copied :(

Maybe this 2-line code snippet is more clear? It's the master parent `xpub` (no derivation needed).

https://github.com/cryptoadvance/specter-desktop/blob/5cc92c989f6d071da6d936c06e0ba5629f03b7ce/src/cryptoadvance/specter/helpers.py#L126-L128

**Comment by merland** [comment]
This was really helpful, thanks! 
I was able to run the specter snippet and got a js unit test working now.

**Comment by merland** [comment]
This is implemented on [seedpicker.net](http://seedpicker.net/calculator/last-word.html) now (Cache reset may be necessary).  
Please advise on wording and appearance.

**Comment by mflaxman** [comment]
The functionality looks great, thanks! I tested it against my python and golang scripts for `zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo buddy` and it correctly returns `669dce62`.

I did notice a security vulnerability on this PR that I think should be addressed ASAP:
https://github.com/merland/seedpicker/commit/8421201e0229ff0e68fea5613cc30311716530ee#r41919841

**Comment by mflaxman** [comment]
Btw, I'm closing this as it's done, right? Love the new feature!
