### ISSUE TITLE
Trailing Space Breaks xpub/Zpub/XFP Calculation!

### ISSUE THREAD

**Issue by mflaxman** [merland/seedpicker#29]
This tool is smart about checking that each word is in the BIP39 wordlist, but then seems to allow spaces to affect its calculation.

I didn't test leading space, but I suspect it would have the same problem.

cc @merland since this one is potentially quite serious.

**Comment by mflaxman** [comment]
Screenshot of `zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo ` (notice the trailing space) for reference.

![Screenshot_2020-09-16 SeedPicker](https://user-images.githubusercontent.com/448644/93349107-b04ee080-f7fc-11ea-836f-e606af70c346.png)

This is the result it should get:
https://github.com/merland/seedpicker/issues/23#issuecomment-683936740

**Comment by merland** [comment]
Ok, should be fixed now. The raw phrase was mistakenly being used instead of the "cleaned" one, in one place. Thanks for the report @mflaxman !! 
I will do some more tests do make sure no more similar bugs exist.

**Comment by mflaxman** [comment]
Thanks @merland for fixing this so quickly! I'm doing my first (of many) podcast interviews this afternoon and am excited to start promoting seedpicker :)

**Comment by merland** [comment]
Wow, cool! Where can I listen to those interviews?

**Comment by mflaxman** [comment]
Just follow me on Twitter! IIRC you already do. Same handle as GitHub: "@mflaxman".
