### ISSUE TITLE
req: Change PDF into GUIDE.md + image files for the tables

### ISSUE THREAD

**Issue by sesam** [merland/seedpicker#3]
Suggest / request to make the pdf into a markdown file, so it can be easily iterated on right here on github, and for easier change tracking.

Maybe GUIDE.md is a suitable filename.

The tables probably can't be in markdown, or are hard to handle, but they can be saved in this repo as .PNG or .SVG and inline included.

TEST: afterwards, verify that printing "just works"

From a security point of view, loading a pdf from anywhere can be risky. And this .pdf will be loaded by coin owners and might become a target. Comparing pdf versions is also hard to do, losing change tracking.

**Comment by merland** [comment]
Thanks for your comment. My aim is definitely to not use pdf in the (near) future. For the first version this was very convenient though. Since printing the document is required, it is crucial that the print looks good.

**Comment by merland** [comment]
GUIDE.md created. The guide works well even if page breaks or margins end up in unintended places, so having it as markdown brings much more pros than cons.
Keeping the other docs as pdf for now, but images are a good idea for the future.
