### ISSUE TITLE
Hard to toggle between mainnet and testnet

### ISSUE THREAD

**Issue by mflaxman** [merland/seedpicker#31]
Creating a new issue because #30 has become a mono-issue beast!

Currently, if you want to use seedpicker on testnet (as everyone should before using it for real), you either have to know [this (semi-secret) URL](https://seedpicker.net/calculator/last-word.html?network=testnet), or do the following steps:
1. Enter 23 words (or easier hit `Generate sample`)
2. Hit `Calculate`
3. Hit `Show more`
4. Hit `switch to testnet` (and then re-enter your 23 words)

Testnet is a fantastic free resource that you can use with a faucet (no need to touch your real BTC), and as bitcoin fees increase it will only get comparatively more valuable. Cobo Vault recently added support for testnet and all other multisig wallets do, so I'm going to update my guide to recommend users start with testnet.

Recommendation: have some sort of toggle for testnet/mainnet before/separate from entering 23 words. It could be in the header, footer, near the calculate button, or somewhere else.

I could even see a version in the future where you disable the sample generation feature on mainnet only, but obviously that's another story altogether and I don't have a strong opinion there. All I can say is that I haven't audited the RNG implementation and like that I don't have to :)

**Comment by merland** [comment]
This may actually be something that we feel a bit differently about :) 

I respect your view that testnet is fantastic but personally I have always just experimented with really small amounts on mainnet. I am open to change my mind in the future, however, and one strong factor in that direction may be the increasing miner fees on mainnet.
 
I think adding testnet to SeedPicker was a good thing, but I also like that the toggle currently is hidden under "Show more". For new users all these new terms and concepts may be difficult to take in, and introducing the concept of testnet too early may make the situation worse for them. Let's see how this progresses, but right now I don't feel that this should be prioritized. 

About the RNG implementation: Yeah, that is maybe SeedPicker's most important message: Don't trust (software) RNGs :)

**Comment by mflaxman** [comment]
Fine to agree to disagree! The most important part is that you have the functionality if people are motivated to find it. Closing for now.
