### ISSUE TITLE
Not obvious that seedpicker is open source!

### ISSUE THREAD

**Issue by mflaxman** [merland/seedpicker#32]
If you arrive directly at https://seedpicker.net/calculator/last-word.html (say from an external link like my guide), there's no github link (like there is in the footer of https://seedpicker.net/).

**Comment by merland** [comment]
Good point. I added contact info on the bottom of the guide page yesterday, partly for this purpose. But that info is one step removed (link in the intro). 
I'll fix a badge or similar. Thanks for the heads-up.

**Comment by bitcoinheiro** [comment]
Yes, user should be recommended to download your repo from github to run offline. Also - remove Google tracker

**Comment by merland** [comment]
No need to download from Github, you can just go offline as soon as the page has loaded in the browser. This is in the instructions. If you use an air-gapped computer, you can instead download the page using your hot computer and then run it from a USB stick or similar. 

I thought the Google tracker was a pretty innocent and easy way for me to get some kind of indication of how much SeedPicker is being used. Or at least checking it out. The offline case is of course already a blind spot.

**Comment by bitcoinheiro** [comment]
Yeah, we're very adverse to trackers in our wallet related software. I understand your motivations, but personally I cannot recommend users to access the website. Maybe you can use a tracker that will not bring a big data corp into the process?
