### ISSUE TITLE
Link to btcguide

### ISSUE THREAD

**Issue by merland** [merland/seedpicker#36]
SeedPicker is now incorporated in both the SeedPicker guide and the 10x Bitcoin Security Guide. 
The caution text urges the user to read the SeedPicker guide only. The user should be presented with both options.

**Comment by merland** [comment]
I deep linked to the paper wallet page. 
Thoughts, @mflaxman?

**Comment by mflaxman** [comment]
Sounds like I need to rent a monkey for a demo video asap!
