### ISSUE TITLE
feat: change short urls into instructions what to google/duckduck for and enough text from the url to be able to verify the correct search engine hit before opening the url

### ISSUE THREAD

**Issue by sesam** [merland/seedpicker#4]
hacks and takeovers of old domains happens all the time. Engines like duckduckgo are fairly free of tracking, and supplies some added security against typosquatters. Apart from safety it is also easier to not make mistakes by typing in search words and verifing the resulting URL, than typing the url directly. In the average case.

**Comment by merland** [comment]
Thanks for your comment, and I agree of course. I plan to put the needed code on custom domain soon.

**Comment by merland** [comment]
Connected this repo to github pages and hooked up [seedpicker.net](https://seedpicker.net).
