### ISSUE TITLE
create a release

### ISSUE THREAD

**Issue by k9ert** [merland/seedpicker#40]
It would be helpfull to have a tagged release in order to be sure what has been the status at a specific point in time.

**Comment by merland** [comment]
Thanks for your interest in SeedPicker, @k9ert!

Would you care to elaborate a little what it is that you would gain from having official releases? Nice to have, sure, but they may also act as speed bumps to the development process. 
If this is about trusting/auditing of the code, you should remember that if you use SeedPicker offline and wipe the hard drive afterwords (or not even use a hard drive), you don't have to trust the SeedPicker code at all! No hacker can change the 23 words written on your piece of paper.
 
The above goes for the 24th word part.  The XPUB generation does involve some "trust" in the SeedPicker code, but the XPUB should be verified using other implementations anyway.
