### ISSUE TITLE
Testnet displays xpub instead of tpub

### ISSUE THREAD

**Issue by mflaxman** [merland/seedpicker#44]
`abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon`

<img width="1132" alt="Screen Shot 2021-06-06 at 4 48 27 PM" src="https://user-images.githubusercontent.com/448644/120942557-6cd03580-c6ef-11eb-8dcb-36e54570ff52.png">

I'd expect `tpubDFkN51vYF36W4Yfn3wGv5fpmRo3ok7vZZjc1gmRJjumq33L776e6GkP4HGdCVjDqYiBahXCrXQKja8aUZ2xovQNS8WkF46MdY7TLHJLYD7H` to be displayed (or at least a way to see that somewhere on the screen without using [this tool](https://jlopp.github.io/xpub-converter/).

**Comment by merland** [comment]
Thanks for this suggestion @mflaxman! Could you elaborate a little more on the use case? I have limited experience with testnet. Would it make most sense to display it inside the "Specter box" or under Show More?

**Comment by merland** [comment]
Thanks for the clarification, seems like a no-brainer. If someone needs the `xpub` for the testnet case, that can be added upon request.

I'm not sure when I can do this but hopefully soon. 
 
> I assume the "Specter box" means the "Show QR" lightbox? 
Yeah sorry, I was referring to the text "This box contains everything you need to export your extended public key to Specter Desktop."

**Comment by merland** [comment]
@mflaxman Sorry for the delay, but this should work now. I changed the label to 

`Extended Public Key in base format (xpub for mainnet and tpub
                for testnet)` 

What are your thoughts on the term "base format"? I find it hard to find the perfect term to use since "xpub" can have different meanings...

**Comment by mflaxman** [comment]
I like base format, although I agree it seems imperfect. I don't have a better term. I think better to add the functionality for now and you can always change the copy later!
