### ISSUE TITLE
Show all possible checksum words for people to select from it randomly

### ISSUE THREAD

**Issue by levelgigio** [merland/seedpicker#45]
Given the 23 words randomly selected, show all words that makes the seed valid, so people can pick one from it randomly and have more transparency in the whole process of seed creation.

**Comment by merland** [comment]
Hi @levelgigio and thanks for your feedback. In an early version of SeedPicker, the last word was indeed selected randomly, but we decided that the risk of user error with that approach is too great. Please read [this comment](https://github.com/merland/seedpicker/issues/13#issue-499534503) from @mflaxman where he outlines the dangers involved. 
The only drawback of preselecting one word is a very small loss of entropy. An entropy that an attacker could brute-force very easily anyway.
