### ISSUE TITLE
12 word seed version requested

### ISSUE THREAD

**Issue by freddiemacd** [merland/seedpicker#8]
I would like to use this for generating a 12 word seed for a hardware wallet.  Can you make a version for that?

**Comment by merland** [comment]
Thanks for submitting this feature request. This is certainly doable. I will probably implement it first in the calculator only, ie without changing any of the instructions in the guide.

**Comment by merland** [comment]
The last word calculator has now been updated to handle 12-word seeds as well as 24-word seeds.
